[[Julia]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "af32d630cb3358c26bd5f03c788fccf9c8ff0ea5"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[Julia.download]]
    sha256 = "0f2b9678eceb33fe304258988ab99e0a74050c2bc13f49f5cb7947ad3c1c8282"
    url = "https://github.com/JuliaBinaryWrappers/Julia_jll.jl/releases/download/Julia-v1.4.2+0/Julia.v1.4.2.aarch64-linux-gnu-libgfortran4-cxx11.tar.gz"
[[Julia]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0cceef9fe2098ad22e9ff5378994ab7393db61ee"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[Julia.download]]
    sha256 = "8d62670127fe0c183fc304bcb2380e539d02423afd8b498270517a0dea7b1854"
    url = "https://github.com/JuliaBinaryWrappers/Julia_jll.jl/releases/download/Julia-v1.4.2+0/Julia.v1.4.2.i686-linux-gnu-libgfortran4-cxx11.tar.gz"
[[Julia]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c5032940cd3fd4386b1763fa920c4763bd7d6ff1"
libgfortran_version = "4.0.0"
os = "macos"

    [[Julia.download]]
    sha256 = "d74340b33827ce4704e64504119bfbe764e87c7bccc9527d43a4f060e51542ba"
    url = "https://github.com/JuliaBinaryWrappers/Julia_jll.jl/releases/download/Julia-v1.4.2+0/Julia.v1.4.2.x86_64-apple-darwin14-libgfortran4-cxx11.tar.gz"
[[Julia]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "23fa1d507e98e6acb856c3b7527bacc294d77254"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[Julia.download]]
    sha256 = "0206c5bf427c6cb611fb0575baef00a4dd002932d5c5ee1590af51791e734d02"
    url = "https://github.com/JuliaBinaryWrappers/Julia_jll.jl/releases/download/Julia-v1.4.2+0/Julia.v1.4.2.x86_64-linux-gnu-libgfortran4-cxx11.tar.gz"
[[Julia]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5aa781aff4c9303f785fcaad0cb03ef59a286b46"
libgfortran_version = "4.0.0"
os = "freebsd"

    [[Julia.download]]
    sha256 = "c18e9ecdc6ff87fe198ff4b7c33d331423d6655d73bb38d84147991831d6cfb9"
    url = "https://github.com/JuliaBinaryWrappers/Julia_jll.jl/releases/download/Julia-v1.4.2+0/Julia.v1.4.2.x86_64-unknown-freebsd11.1-libgfortran4-cxx11.tar.gz"
